name: Python-test

on:
  push:
    branches: [main]
    
jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install and run Xvfb (virtual display for headless browsers)
        run: |
          sudo apt-get install xvfb
          Xvfb :99 & export DISPLAY=:99

      - name: Run Pytest with Selenium
        run: |
          export DISPLAY=:99
          pytest
